### ISSUE TITLE
reCaptcha missing on contact page

### ISSUE THREAD

**Issue by michelecanal** [magento/magespecialist_ReCaptcha#21] opened 2018-12-06 17:36 UTC
We have noticed a bug. reCaptcha is missing on the contact page.
Only sometimes appear

Preconditions

1.  - Magento 2.3
2.  - MSP reCaptcha v2.0.2

Page Cache Type - Built In (PHP)
All Caches enabled
Steps to reproduce
Enabled reCaptcha (invisible or V2) on contact page
Flush the cache after the config changes
Go to the contact page

Expected result
reCaptcha is visible

Actual result
Invalid reCaptcha Error message displayed
reCaptcha is MISSING.

**Comment by phoenix128** [comment] 2019-04-18 13:40
Thank you @michelecanal for reporting this issue.
The problem is fixed in https://github.com/magento/magespecialist_ReCaptcha/pull/37 .

**Closed by phoenix128** 2019-04-18 13:40 UTC
Labels: PR available
