### ISSUE TITLE
Not displaying on custom registration form

### ISSUE THREAD

**Issue by killday** [magento/magespecialist_ReCaptcha#59] opened 2019-10-01 10:18 UTC
### Preconditions

1. Magento 2.2.0
2. Php 7.1.32

### Steps to reproduce

1. Install & Configure
2. Create custom registration form which is copy of the standard one + custom input fields 
3. Add the form to CMS page

### Expected result

1. reCaptcha display on the custom form
It display properly on the standard form
![image](https://user-images.githubusercontent.com/6714294/65953988-0b959080-e43d-11e9-92ce-98197df17c2a.png)

### Actual result

1. Not displaying on the custom form
![image](https://user-images.githubusercontent.com/6714294/65954031-25cf6e80-e43d-11e9-85c8-bff78386bb99.png)

**Comment by phoenix128** [comment] 2019-11-07 09:22
This is a duplicate of https://github.com/magento/magespecialist_ReCaptcha/issues/43

**Closed by phoenix128** 2019-11-07 09:22 UTC
